steps:
  - name: node
    id: 'Install packages'
    args: ['yarn','install']

  - name: node
    id: 'Package security check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        yarn global add audit-ci
        audit-ci --report-type=full